### ISSUE TITLE
Feature Request: Add Fraction#isInteger() or similar

### ISSUE THREAD

**Issue by lorenzleutgeb** [Hipparchus-Math/hipparchus#115]
I am using `org.hipparchus.Fraction` and would like to know whether a specific object of this class represents an integer number or not. Of course I know that I could just get the denominator, and check whether it is one. But that's cumbersome and I feel that Hipparchus should do this job for me. I therefore request the addition of `org.hipparchus.Fraction#isInteger()`.

My current implementation is:

```java
public static boolean isInteger(Fraction fraction) {
  return 1 == fraction.getDenominator();
}
```

I am happy to provide a PR upon request.

@maisonobe I'll tag you here since you were kind enough to handle my last request. Thanks 😊

**Comment by maisonobe** [comment]
Sure, we could add this.
Please provide a pull request (with tests) and we will review it for inclusion.
