### ISSUE TITLE
Implement Jacobi elliptic functions

### ISSUE THREAD

**Issue by maisonobe** [Hipparchus-Math/hipparchus#119]
These functions are useful in modeling some physics problems.
The major functions are sn, cn, and dn, but there are twelve different functions (cd, sd, nd, dc, nc, sc, ns, ds, cs)
as well as associated theta functions.
They are described in the classical handbook of mathematical functions (Abramowitz and Stegun, chapter 16, but maybe chapter 17 on elliptic integrals could be helpful too) and in NIST Digital Library of Mathematical Functions, [chapter 22](https://dlmf.nist.gov/22).

**Comment by axkr** [comment]
Do you also implement versions for `Complex` numbers?

**Comment by maisonobe** [comment]
Yes, the functions are available for all `CalculusFieldElement`, including Complex.
I did not try it specifically on Complex, though.
