### ISSUE TITLE
Performance improvement for Array2DRowRealMatrix.getSubMatrix()

### ISSUE THREAD

**Issue by ebourg** [Hipparchus-Math/hipparchus#12]
Hi the Hipparchus Team :)

A performance improvement to `Array2DRowRealMatrix.getSubMatrix()` has been applied recently to Commons Math, you may be interested in applying it as well:

https://issues.apache.org/jira/browse/MATH-1389
https://github.com/apache/commons-math/commit/72df12fb2ba453afb57cf185d25c502d4daec6d1

With this modification the performance is significantly better when the method hasn't been compiled by the JIT yet (or with non Hotspot JVMs). Once the JIT kicked in its roughly equivalent to the current implementation.

**Comment by psteitz** [comment]
On 10/12/16 7:05 AM, Emmanuel Bourg wrote:
>
> Hi the Hipparchus Team :)
>
> A performance improvement to |Array2DRowRealMatrix.getSubMatrix()|
> has been applied recently to Commons Math, you may be interested
> in applying it as well:
>
> https://issues.apache.org/jira/browse/MATH-1389
> apache/commons-math@72df12f
> <https://github.com/apache/commons-math/commit/72df12fb2ba453afb57cf185d25c502d4daec6d1>
>
> With this modification the performance is significantly better
> when the method hasn't been compiled by the JIT yet (or with non
> Hotspot JVMs). Once the JIT kicked in its roughly equivalent to
> the current implementation.
>

Thanks, Emmanuel!

Phil
