### ISSUE TITLE
SNAPSHOT 2.0 - CalculusFieldElement.abs() returns Complex

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#124]
Abs returns a `Complex` value:

```
Complex org.hipparchus.CalculusFieldElement.abs()
```

In older releases it returned a `double`.

Should `norm` and `abs` both return a `Complex` number now?
For existing code it will probably be easier if `abs()`return a `double` value.

On the other hand reading the Wikipedia pages
- https://en.wikipedia.org/wiki/Norm_(mathematics)
- https://en.wikipedia.org/wiki/Absolute_value

it will be more "natural" to return a `double` for the `norm` method.

**Comment by maisonobe** [comment]
This was the can of worms that mainly triggered the release of 2.0.
Both types (double and the Complex/Dfp/Derivative/you name it) are logical answers.
I would prefer to completely remove abs and keep only norm, with a return type set
to the field.

But this is *only* my point of view, so I would like to see what other developers and users think.

**Comment by axkr** [comment]
I prefer to let `norm` return a `double` value in the sense that it represents a "distance".

And let `abs` return the `Complex`number.
