### ISSUE TITLE
SNAPSHOT-2.0

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#131]
Should `JacobiTheta()` be protected and not directly used?
- https://github.com/Hipparchus-Math/hipparchus/blob/6694bb1c45fe714785677f2859931ce2fcbc96f6/hipparchus-core/src/main/java/org/hipparchus/special/elliptic/JacobiTheta.java#L55

**Comment by maisonobe** [comment]
It's a bug! It should be public.

I'll fix it in a few minutes.

**Comment by maisonobe** [comment]
Fixed in master brach.
Thanks for the report!

**Comment by axkr** [comment]
Same for `FieldJacobiTheta`?

**Comment by maisonobe** [comment]
Yes, I forgot it.

Note also that in the same package, the elliptic integrals (both Legendre and Carlson) are not complete yet
and there are known bugs I am working on. I hope to finalize this package this week.

**Comment by maisonobe** [comment]
We could provide these helper methods, sure. Please open a new issue for that so we don't forget about them.
Concerning caching, I prefer to let the user handle it. Depending on the problem to solve, the parameter m is either fixed or changes at each call. If it changes, caching would either consume a lot of memory or some strategy last least recently used eviction would be needed, and it would not be worth doing.

**Comment by axkr** [comment]
I'm thinking of a very simple cache by comparing `m` with the last value used in `JacobiEllipticBuilder`?
