### ISSUE TITLE
Can  CalculusFieldElement#signum() return an int value?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#138]
Is there any reason, why 
```
CalculusFieldElement#signum()
```

should return `T`? I think an `int` value for `-1,0,1` should be enough?

What is the difference to the sign function which is defined as `z/Abs(z)` for complex values?
- https://functions.wolfram.com/ComplexComponents/Sign/introductions/ComplexComplements/ShowAll.html
- https://mathworld.wolfram.com/Sign.html

In my project `signum()` definition clashes with definition from JAS:
- https://github.com/kredel/java-algebra-system/blob/ccb6b5718edc3712a5d7c50dd00fc9e368075291/src/edu/jas/structure/AbelianGroupElem.java#L28

**Comment by maisonobe** [comment]
This is for consistency with `Math.signum()` (and therefore also `FastMath.signum()`).
An int would not be sufficient as signum(NaN) returns a NaN.

**Comment by axkr** [comment]
And what about the definition for the `Complex#sihnum()`? Should it be changed to `z/Abs(z)`

**Comment by maisonobe** [comment]
Yes, I think `a/abs(z)` would be a better implementation.

**Comment by axkr** [comment]
I've seen that hipparchus doesn't use `signum()` so much in the core.
Can you please rename it to `sign()` in the `CalculusFieldElement` interface to avoid the name clash.

Otherwise I have to create an extra "delegate class" which from my view shouldn't be necessary.

**Comment by axkr** [comment]
But as a Java interface which other users should implement if they use hipparchus, it's not usable, because it will immediately clash with other signum functions of other Java interfaces.

Thereas the `sign` name seems to me more perfect:
- https://reference.wolfram.com/language/ref/Sign.html

**Comment by maisonobe** [comment]
OK, I have changed the name.

This had a nasty side effect and I deleted the `Signum` class entirely because it did not fit anymore with the test harness because the function name between `Math`/`StrictMath`/`FastMath` and `CalculusFieldElement` do not match anymore.

**Comment by maisonobe** [comment]
The continuous integration worked and the snapshot artifacts were pushed, so they are available.
Could you check if this suits your needs?
