### ISSUE TITLE
Complex#atan2()

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#140]
```
          Complex cx=new Complex(2,0);
    	  Complex cy=new Complex(0,4);
    	  System.out.println( cx.atan2(cy)); 
```

gives `(0.0, -0.5493061443340549)` but should give `1.5707963267948966+I*0.5493061443340549*`

https://www.wolframalpha.com/input/?i=atan%282%2CI*4%29

**Comment by maisonobe** [comment]
Beware that in Wolfram alpha, it seems that the two argument atan function is interpreted as tan^-1(x, y) (see the input interpretation panel in the result page), whereas in Hipparchus
(and in all programming languages I have seen), the first argument of atan2 is y and the second is x.
Also as one imaginary part is zero and the real part of the other number is zero, one should check with tiny positive and negative values to see if there is a branch cut. In this case, there is one and putting the arguments in the other order give the same result as Hipparchus:

https://www.wolframalpha.com/input/?i=atan%28%2B1.0e-8%2BI*4%2C+2%2B1.0e-8+I%29

note that changing the sign of the almost zero real part changes the output:

https://www.wolframalpha.com/input/?i=atan%28-1.0e-8%2BI*4%2C+2%2B1.0e-8+I%29

So I would say the Hipparchus result is correct here.

**Comment by axkr** [comment]
OK.
Does it make sense to add some note to javadoc here:
- https://github.com/Hipparchus-Math/hipparchus/blob/2b59ff32acf39b65aa68188a3895d6c71ae22752/hipparchus-core/src/main/java/org/hipparchus/CalculusFieldElement.java#L223

**Comment by maisonobe** [comment]
Good idea, I have updated documentation.
