### ISSUE TITLE
FieldLUDecomposition()

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#144]
- https://github.com/Hipparchus-Math/hipparchus/blob/7017b798bbdfe6664106ba81a8677b15f77b1d29/hipparchus-core/src/main/java/org/hipparchus/linear/FieldLUDecomposition.java#L191

Insert:

```
  if (max >= m) {
    max = m-1;
  }
```

to avoid
```
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.hipparchus.linear.FieldLUDecomposition.<init>(FieldLUDecomposition.java:196)
	
```

**Comment by axkr** [comment]
- https://github.com/Hipparchus-Math/hipparchus/blob/1a794c1b2c5412e3c75d5681097ac5232be155cb/hipparchus-core/src/main/java/org/hipparchus/linear/FieldLUDecomposition.java#L191

Shouldn't this be ` max = FastMath.min(m - 1, nonZero);`

**Comment by maisonobe** [comment]
Of course, you're right!
Sorry for the stupid error.
