### ISSUE TITLE
OrderedComplexEigenDecomposition user defined sorting

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#173]
The fields `eigenvalues` and `eigenvectors` in `ComplexEigenDecomposition` didn't get sorted in `OrderedComplexEigenDecomposition`.
Only `D` and `V` get sorted.

How can I define my own sorting and get these fields also refreshed?

https://github.com/Hipparchus-Math/hipparchus/blob/c816b0e811ba18f52b3f00b46bccd3f0a14784ff/hipparchus-core/src/main/java/org/hipparchus/linear/OrderedComplexEigenDecomposition.java#L59

**Comment by maisonobe** [comment]
Is is a bug.
I have fixed it in master branch, could you check if it works for you now?

**Comment by axkr** [comment]
Can you also introduce a constructor for `FieldMatrix<Complex> matrix` parameter?

**Comment by maisonobe** [comment]
Not easily.
We don't have eigen decomposition implemented in the general case, only in the real case (which however does provide
results as complex numbers when the real matrix has complex eigenvalues).
Could you open a new issue labeled as "Feature" to ask for implementing this feature?

**Comment by axkr** [comment]
Done #174
