### ISSUE TITLE
Implement the Gram Schmidt process 

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#178]
Please implement the Gram Schmidt process for the `FieldMatrix<T>` class type  as a method to return the orthonormal basis for some given vectors.

**Comment by maisonobe** [comment]
Two `orthonormalize` methods have been added to `MatrixUtils`. One for double-based lists of vectors, one for CalculusFieldElement-based lists of vectors.

**Comment by axkr** [comment]
I assume, if some of the input vectors are not linearly independent, the output should contain zero vectors?

```
    @Test
    public void testOrthonormalize4() {
        final List<RealVector> basis =
                        MatrixUtils.orthonormalize(Arrays.asList(new ArrayRealVector(new double[] { 2, 3 }),
                                                                 new ArrayRealVector(new double[] { 2, 7 }),
                                                                 new ArrayRealVector(new double[] { 4, 5 })));
        Assert.assertEquals(3, basis.size());
        checkVector(basis.get(0), 0.5547001962252291, 0.8320502943378437);
        checkVector(basis.get(1), -0.8320502943378437, 0.5547001962252291);
        checkVector(basis.get(2), 0.0, 0.0);

    }
```

**Comment by maisonobe** [comment]
It should throw an exception. In this case, due to the normalization process, when the third vector is processed, it has a very small non-zero norm (its components are -4.44e-16 and -6.11e-16), so it is computed as a regular vector.

I will add an additional argument with a threshold on norm to consider such small norms as zero and to throw an exception there.

**Comment by axkr** [comment]
Sorry I thought, that instead of an exception the `0`-vectors can be added to the result.

**Comment by maisonobe** [comment]
This looks rather awkward to me as an API.
What should we do if the dependent vector is the 3rd one but a 4th vector afterwards is independent? Should we
still put the 0 vector as the 3rd one in the list? 
Another possibility (which I would prefer), would be to just ignore the vector ant continue the loop, so in the previous case with 4 vectors and the 3rd one dependent of the first two, we would return a list of length 3 built from vectors 1, 2 and 4. The mathematical meaning would be: " we return a basis of the span of the input vectors ". The returned list would always be a basis. Including a zero vector, we don't have a basis anymore.
I think in this case we should add a boolean flag to et the user either throw an exception or return a basis of the span.

**Comment by axkr** [comment]
I'm trying to match this API:
- https://reference.wolfram.com/language/ref/Orthogonalize.html

**Comment by maisonobe** [comment]
It still seems awkward to me. Enforcing the fact to keep the same number of vectors by adding zero vectors if the span dimension is less then the number of vectors is not mathematically sound to me. The description reads "gives an orthonormal basis". With zero vector, it is not an orthonormal basis, where all vectors are normalized.
I will launch a thread on the forum to gather opinions from other users.

**Comment by maisonobe** [comment]
The topic in the forum is here: [Deciding about an API for Gram-Schmidt orthogonalization feature ](https://forum.orekit.org/t/deciding-about-an-api-for-gram-schmidt-orthogonalization-feature/1551)

**Comment by maisonobe** [comment]
As per discussion above, I implemented all three choices : generate exception, add zero vector or reduce basis to span.
