### ISSUE TITLE
`RandomDataGenerator.nextSecureHexString` seems to be missing. 

### ISSUE THREAD

**Issue by hmf** [Hipparchus-Math/hipparchus#179]
I am trying to use `nextSecureHexString` in version 2.0 as per the [documentation](https://hipparchus.org/hipparchus-core/random.html#Random_Strings). The IDE reports the method is not a member of `RandomDataGenerator`. A look at jar's source code and a searched in this repository seems to indicate that this is so. 

Has this been removed or is this available elsewhere?

TIA.

**Comment by maisonobe** [comment]
Yes, secure strings have been removed from the library a long time ago.
It seems we did not fix this part of the documentation :-(

**Comment by hmf** [comment]
@maisonobe If you like, I can open a new issue as incorrect documentation.

**Comment by maisonobe** [comment]
Sure, this will allow us to remember to fix that.
