### ISSUE TITLE
Incorrect documentation: use of `nextSecureHexString` for generating random strings.

### ISSUE THREAD

**Issue by hmf** [Hipparchus-Math/hipparchus#180]
The `nextSecureHexString` has been removed from the library but is still in the [documentation](https://hipparchus.org/hipparchus-core/random.html#Random_Strings). This is a followup of #179. I suspect other cryptographically secure methods have also be removed because I find no references to these in the API documentation ad source.

**Comment by maisonobe** [comment]
Fixed in master branch.

Thanks for the report!
