### ISSUE TITLE
NOT_BRACKETING_INTERVAL in event detection for rare reset cases

### ISSUE THREAD

**Issue by maisonobe** [Hipparchus-Math/hipparchus#184]
In ODE, when an event generates a RESET_STATE, the step is truncated, state is reset, and the next step will start from the event date. In some cases, either due to the reset itself or to numerical noise as the step interpolator changes, the value g(t_event) may change sign. This case has been considered in `EventState.findRoot`, with the following code:
```java
    final double newGa = f.value(ta);
    if (ga > 0 != newGa > 0) {
        // both non-zero, step sign change at ta, possibly due to reset state
        beforeRootT = ta;
        beforeRootG = newGa;
        afterRootT = minTime(shiftedBy(beforeRootT, convergence), tb);
        afterRootG = f.value(afterRootT);
    }
```

However, in the next lines, these variables are not used when starting the search loop, the initial values `ta` and `ga` are used:
```java
  // loop to skip through "fake" roots, i.e. where g(t) = g'(t) = 0.0
  // executed once if we didn't hit a special case above
  double loopT = ta;
  double loopG = ga;
  while ((afterRootG == 0.0 || afterRootG > 0.0 == g0Positive) &&
         strictlyAfter(afterRootT, tb)) {
      ....
  }
```

When the reset has changed the sign of `ga`, and there is also a second zero in the first half of the check interval (i.e. between `ta` and `(ta+tb)/2`), then `f(ta)`, `f((ta+tb)/2)` and `f(tb)` all have the same sign. This triggers a NOT_BRACKETING_INTERVAL exception when `solver.solveInterval()` is called.

The following test case reproduces the error:
```java
    @Test
    public void testResetChangesSign() {
        OrdinaryDifferentialEquation equation = new OrdinaryDifferentialEquation() {
            public int getDimension() { return 1; }
            public double[] computeDerivatives(double t, double[] y) { return new double[] { 1.0 }; }
        };

        LutherIntegrator integrator = new LutherIntegrator(20.0);
        final double small = 1.0e-10;
        ResetChangesSignGenerator eventsGenerator = new ResetChangesSignGenerator(6.0, 9.0, -0.5 * small);
        integrator.addEventHandler(eventsGenerator, 8.0, small, 1000);
        final ODEStateAndDerivative end = integrator.integrate(equation, new ODEState(0.0, new double[1]), 100.0);
        Assert.assertEquals(2,                 eventsGenerator.getCount());
        Assert.assertEquals(9.0,               end.getCompleteState()[0], 1.0e-12);
        Assert.assertEquals(9.0 + 0.5 * small, end.getTime(),             1.0e-12);
    }

    private class ResetChangesSignGenerator implements ODEEventHandler {

        final double y1;
        final double y2;
        final double change;
        int count;

        public ResetChangesSignGenerator(final double y1, final double y2, final double change) {
            this.y1     = y1;
            this.y2     = y2;
            this.change = change;
            this.count  = 0;
        }

        public double g(ODEStateAndDerivative s) {
            return (s.getCompleteState()[0] - y1) * (s.getCompleteState()[0] - y2);
        }

        public Action eventOccurred(ODEStateAndDerivative s, boolean increasing) {
            return ++count < 2 ? Action.RESET_STATE : Action.STOP;
        }

        public ODEState resetState(ODEStateAndDerivative s) {
            return new ODEState(s.getTime(), new double[] { s.getCompleteState()[0] + change });
        }

        public int getCount() {
            return count;
        }

    }
```

Changing the initialization of `loopT` (resp. `loopTG`) to `afterRootT` (resp. `afterRootT`) solves this specific case, but it breaks `OverlappingEventsTest`.

The same issue exists in Orekit (but I have no test case for it).

**Comment by wardev** [comment]
Nice find!

If I remember my own work correctly I think it was supposed to not execute the loop in this case. But perhaps if f(ta + convergence) is zero or there is a second root in that short interval it wouldn't work. Needs some more thought...

**Comment by maisonobe** [comment]
I tried to solve it but did not succeed yet.
I guess that the culprit is in the snippet
```java
if (ga > 0 != newGa > 0) {
        // both non-zero, step sign change at ta, possibly due to reset state
        beforeRootT = ta;
        beforeRootG = newGa;
        afterRootT = minTime(shiftedBy(beforeRootT, convergence), tb);
        afterRootG = f.value(afterRootT);
    }
```
We should probably compare the sign of `newGa` and the boolean `g0positive` to see if we have a new
root that appeared due to reset and it should be reported as a new event occurring (I guess this is what this snippet does), or if it is the same root we already handled and that moved (this is what happens in the bug), and in this case I think it should be ignored, looping with `shifttedBy(t, convergence)` until we are past the already handled root, and we can search for the next root that occurs in the step (otherwise `findRooot` would not have been called) once we are sure we won't trigger a non-bracketing exception.

I am however not sure about this analysis, and will not be able to look at it before some time.

@wardev , could you have a look at it?

**Comment by maisonobe** [comment]
Finally found some free cycles to solve this.

**Comment by wardev** [comment]
Nice fix, glad you figured it out. I added some tests for reverse integration as well.
