### ISSUE TITLE
new Complex(-0.0).getArgument()  should return 0.0?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#185]
Not sure, but should the result be `0.0` in both cases?

```
public void testArg() {
    System.out.println(new Complex(0.0).getArgument());
    System.out.println(new Complex(-0.0).getArgument());
}
```

**Comment by maisonobe** [comment]
I am not sure either. I think it should be compliant with atan2, but even this seems to have different implementations in different systems. See for example [https://fr.mathworks.com/help/matlab/ref/atan2.html#mw_1040eb57-4de5-47ed-b7ea-aafaaf439ad9](https://fr.mathworks.com/help/matlab/ref/atan2.html#mw_1040eb57-4de5-47ed-b7ea-aafaaf439ad9).

What does Hipparchus return currently?

**Comment by axkr** [comment]
it returns:

```
0.0
3.141592653589793
```

**Comment by axkr** [comment]
Yes I see. 
I think this issue can be closed.
