### ISSUE TITLE
Complex#abs() method which returns a double value

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#186]
Can you please add a `abs()` method variant, which returns a double value for  complex number?
- https://github.com/Hipparchus-Math/hipparchus/blob/18326333cd0853149cc4bc649f1ccf6b7710c371/hipparchus-core/src/main/java/org/hipparchus/complex/Complex.java#L138

**Comment by axkr** [comment]
Ok `norm()` can be used instead but uses a temporary object.

Maybe `norm()` can be overriden in `Complex`?

**Comment by maisonobe** [comment]
It seems to be just the opposite of what was discussed in [issue 67](https://github.com/Hipparchus-Math/hipparchus/issues/67#issuecomment-630633201).

**Comment by axkr** [comment]
I meant a small improvement for `norm()` in Complex:

```
    @Override
    public double norm() {
      // we check NaN here because FastMath.hypot checks it after infinity
      return isNaN ? Double.NaN : FastMath.hypot(real, imaginary);
    }
```
