### ISSUE TITLE
FieldJacobiElliptic#arccn(2.5,0.3) result of imaginary part should be negative

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#189]
The result of the imaginary part of `FieldJacobiElliptic#arccn(2.5,0.3)` should be negative.

```
 final FieldJacobiElliptic<Complex> je = JacobiEllipticBuilder.build(new Complex(0.3));
    System.out.println(je.arccn(new Complex(2.5)));
```

**Comment by axkr** [comment]
Similar case but imaginary part should be positive.

```
    final FieldJacobiElliptic<Complex> je = JacobiEllipticBuilder.build(new Complex(0.7));
    System.out.println(je.arcdn(new Complex(0.3)));
```

**Comment by maisonobe** [comment]
Good catch!
It seems we are struck again by branch cut issues. The following plot shows the value of arccn(0.3, z) for z in the real and imaginary parts between -4 and +4. We see that when the sign of the imaginary part changes near 2.5 ± 0i, there is a branch cut (the color changes from green for negative imaginary to purple for positive imaginary). The branch cut seems to go from +1 to +∞ along the real line.
![arccn](https://user-images.githubusercontent.com/3736196/162964802-08f4917d-ba1e-4ef0-91c3-29eaad49b085.png)

There seem to be other branch cuts along the imaginary lines. They are around [-i∞ ; -π/2i], [+π/2i ; +i∞] along imaginary axis, and perhaps [-∞ ; -π/2] along the negative part of the real axis. I don't know if these values are accurate or no, if they depend on the parameter m (which is 0.3 in this plot) or not. I think the branch cut between +1 and +∞ along the positive real axis is correct.

What is not correct, though, is that if I use a signed zero in the implementation, the value remains positive. It switches to negative only if I use a tiny positive imaginary part.

I have found a paper that seem to address these branch cuts [here](https://researchspace.auckland.ac.nz/bitstream/handle/2292/5042/390.pdf).

**Comment by axkr** [comment]
BTW: which tool do you use for your graphics?

**Comment by maisonobe** [comment]
A tool I developed to help debugging complex functions.
It is in the hipparchus-sample module: [complex plotter](https://github.com/Hipparchus-Math/hipparchus/tree/master/hipparchus-samples/src/main/java/org/hipparchus/samples/complex). It generates the data and calls gnuplot for rendering. When called with `--output-dir  some-arbitrary-directory`, it generates png files in the corresponding directory. When called without this option, it uses an interactive gnuplot terminal (`qt` in my case, despite I use a gnome environment on my Linux system).

**Comment by axkr** [comment]
There are other cases which seem to be wrong, so I don't investigated any further.

In this example the real part is `0.0`:
```
je = JacobiEllipticBuilder.build(new Complex(0.3));
    System.out.println(je.arcdn(new Complex(10.0)));
```

In WolframAlpha it has a real part:
- https://www.wolframalpha.com/input?i=InverseJacobiDN%2810.0%2C0.3%29

**Comment by maisonobe** [comment]
> In WolframAlpha it has a real part:
> 
>     * https://www.wolframalpha.com/input?i=InverseJacobiDN%2810.0%2C0.3%29

The real part returned by Wolfram alpha is 3.427778896357582, which is exactly 2K for parameter m=0.3, where K is the complete elliptic integral of the first kind. As all Jacobi elliptic functions, dn is double periodic (once along the real axis and once along the imaginary axis). Its period along the real axis is 2K (see [DLMF section 22.4 table 2](https://dlmf.nist.gov/22.4#T2).
So returning 0 for the real part seems correct to me.

**Comment by maisonobe** [comment]
The problems identified have been fixed, except for one case with a negative zero in the imaginary part of the argument and a positive zero in the imaginary part of the parameter.
Please note that we do not always return the same value as Wolfram Alpha for the inverse functions. These functions are doubly periodic and have many symmetries, so sometimes we return a value shifted by one period. As an example,[InverseJacobiCS(2.5-0.1 i, 0.3 + 0.1i)](https://www.wolframalpha.com/input?i=InverseJacobiCS%282.5-0.1+i+%2C0.3%2B0.1i%29) returns -3.0359...-0.10108... i in wolfram Alpha, but we return a value that is much closer to origin: 0.38263... + 0.014989...i. The two values differ from one period : 2K (the other period being 4iK' for the cs function, as shown in DLMF [table 22.4.2](https://dlmf.nist.gov/22.4.T2)).
