### ISSUE TITLE
[Feature] Map Inversion of Taylor Series

### ISSUE THREAD

**Issue by MaximeJo** [Hipparchus-Math/hipparchus#190]
Hi all,

As Hipparchus has Taylor expansion capacities embedded in the `DerivativeStructure` class, it would be nice to be able to invert the Taylor expansion and do what it is often called a Taylor map inversion or polynomial partial inversion.

An example of usage in Orekit (which depends on Hipparchus) would be:

- Given an initial state X0 at t0 and a propagation model, compute a first-guess orbital maneuver parameterized with (a,b,c) that leads to a final state Xf at tf
- Obtain the Taylor expansion of Xf depending on the maneuver's parameters: T(Xf) = Taylor(a, b, c)
- Invert the Taylor algebra polynomial to get (a, b, c) = T^(-1)(Xf) as a Taylor expansion.
- Compute (a, b, c) that optimize the maneuver to reach a target state Xt at tf.

Here's a link to a [mathematical method used in another library](http://darioizzo.github.io/audi/utilities.html?highlight=invert_map#_CPPv410invert_mapRKNSt6vectorI7gdual_dEEb).

**Comment by Serrof** [comment]
Hi Maxime,

I strongly support the addition of this feature. This algorithm can be found in the Chapter 2 of Modern Map Methods in Particle Beam Physics by Martin Berz (Academic Press 1999).
Also, be careful with notations: one can only invert a square map (as many functions than variables in the Taylor algebra), but trivial components can be added for that purpose.
A univariate (in that case, this is also called series reversion) example in astrodynamics is Kepler's equation (see https://darioizzo.github.io/audi/notebooks/map_inversion.html).

**Comment by Serrof** [comment]
There are many ways to validate the implementation of this, for instance:
- Inverse of 1D map on any intrinsic function e.g. `exp `will be equivalent to directly calling their reciprocal `log `as a `DerivativeStructure`
- Any inverted map, if composed ("rebased" as per _Hipparchus_' nomenclature) with the original one, will give the so-called identity map.
Luc if you have any interrogations on the process described in Maxime's reference, don't hesitate to ask me. But I reckon that it is rather straightforward compared to more complicated things you handled fine before!
