### ISSUE TITLE
[Feature] Integration and differentiation operators for DerivativeStructure

### ISSUE THREAD

**Issue by Serrof** [Hipparchus-Math/hipparchus#192]
In his seminal work on the Taylor Differential Algebra (see for example [1]), M. Berz proposed to define an integration and differentiation operators on objects representing the partial derivatives of functions up to an arbitrary order (or equivalently, Taylor expansions). Amongst other things, they can be leveraged to implement respectively the Picard and Taylor integrators. Hipparchus already contains DerivativeStructure representing partial derivatives, but does not feature these two special operators.

For the sake of clarity, here are a few more details on them in the univariate case:
If $f(x)=f(0)+f'(0)x + ...+\dfrac{ f^n(0)}{n!}x^n+o_0(x^n)$
then $\int^{x} f(x)=cst + f(0)x +\dfrac{ f'(0)}{2!}x^2 ...+\dfrac{ f^n(0)}{(n+1)!}x^{n+1}+o_0(x^{n+1})$
but the expansion can be stopped at order $n$ to avoid casting the output as a DerivativeStructure of different size.
For differentiation, one would rigorously need to start at order $n+1$ to get the correct result at $n$, but again for practical reasons it is simpler to keep the same one (the user must then be aware of this behavior).

[1] BERZ, A. Differential algebraic description of beam dynamics to very high orders. Part. Accel., 1988, vol. 24, no SSC-152, p. 109-124.

**Comment by maisonobe** [comment]
Fixed in the master branch.
I have merged your fix, with a few changes (coding style, more tests, field version).
Thanks for the patch!
