### ISSUE TITLE
Error case in WelzlEncloser.pivotingBall

### ISSUE THREAD

**Issue by jerdmanGH** [Hipparchus-Math/hipparchus#20]
The following code generates an internal error:

		final WelzlEncloser<Euclidean3D, Vector3D> encloser =
                new WelzlEncloser<Euclidean3D, Vector3D>(1e-14, new SphereGenerator());
		List<Vector3D> points = new ArrayList<Vector3D>();
		points.add(new Vector3D(0.9999999731, 0.000200015, 0.0001174338));
		points.add(new Vector3D(0.9987716667, 0.0350821284, 0.0349914572));
		points.add(new Vector3D(0.9987856181, -0.0346743952, 0.0349996489));
		points.add(new Vector3D(0.9987938115, -0.0346825853, -0.0347568755));
		points.add(new Vector3D(0.9987798601, 0.0350739383, -0.0347650673));
                EnclosingBall<Euclidean3D, Vector3D> enclosing3D = encloser.enclose(points);

**Comment by maisonobe** [comment]
I confirm the issue.
The problem seem to be related to numerical issues. During the enclosing ball search iterations, the radius of the balls should be non-decreasing from one iteration to the next one. However, with the points sample above, one iteration leads to a ball of radius 0.04932531217754311 and at the following iteration the radius becomes 0.049325312177543094 which is 1.6e-17 smaller. The difference is 2 ulps only.
I am looking at this.

**Comment by maisonobe** [comment]
The issue has been fixed in commit https://github.com/Hipparchus-Math/hipparchus/commit/842ccd23911d7a1f294fae2511dd16114d42083c.

Thanks for the report!
