### ISSUE TITLE
RegionFactory intersection observed to return erroneous regions in some edge cases, and the resulting intersection can vary drastically depending on the order of the input args

### ISSUE THREAD

**Issue by JakeRandellOC** [Hipparchus-Math/hipparchus#202]
I believe I have found a bug with the `intersection` method within the `RegionFactory` class. I have noticed two inconsistent behaviours on multiple occasions when handling regions that have small overlapping sections (I'm quantifying "small" here as having surface areas < 1E-11):

- The resultant intersection will often have a larger area than expected, with coordinates that do not make sense to be part of the intersection.
- The order of the `intersection` method inputs can sometimes affect the resultant intersection dramatically.

I have been seeing the same results on both Hipparchus V2.1 and V1.4. The following code can be used to replicate the issue:

```
final static S2Point[] VERTICES1 = {	new S2Point(0.06661351701495737, 1.5632121739978346),
                                                                new S2Point(0.0193428339344826, 1.5537209444301618),
								new S2Point(0.0178197572212936, 1.553415699912148),
								new S2Point(0.01628496406053076, 1.5531081515279537),
								new S2Point(0.0017290116591669167, 1.5501937253332354),
								new S2Point(0.0017287169418702727, 1.5501952178464433),						
								new S2Point(0.06661322099543592, 1.5632136662446017), };

final static S2Point[] VERTICES2 = {	new S2Point(0.0, 1.5707963267948966),
								new S2Point(0.017453292519943295, 1.5707963267948966),
								new S2Point(0.017453292519943295, 1.5533430342749532),
								new S2Point(0.0, 1.5533430342749532),
								new S2Point(0.0, 1.5707963267948966), };
/**
 * Tests the Hipparchus {@link RegionFactory#intersection(Region, Region)}
 * method.
 */
@SuppressWarnings("static-method")
@Test
public void TestIntersectionOrder() {

	final SphericalPolygonsSet sps1 = new SphericalPolygonsSet(1E-10, VERTICES1);
	final SphericalPolygonsSet sps2 = new SphericalPolygonsSet(1E-10, VERTICES2);

	final RegionFactory<Sphere2D> regionFactory = new RegionFactory<Sphere2D>();

	final Region<Sphere2D> intersection1 = regionFactory.intersection(sps1, sps2);
	final Region<Sphere2D> intersection2 = regionFactory.intersection(sps2, sps1);

	final SphericalPolygonsSet intersectionSPS1 = new SphericalPolygonsSet(intersection1.getTree(true), 1E-10);
	final SphericalPolygonsSet intersectionSPS2 = new SphericalPolygonsSet(intersection2.getTree(true),1E-10);

	final List<S2Point> intersectionPoints1 = getLoopPoints(intersectionSPS1.getBoundaryLoops() .get(0));
	final List<S2Point> intersectionPoints2 = getLoopPoints(intersectionSPS2.getBoundaryLoops() .get(0));

	System.out.println("Intersection 1:");
	System.out.println("Size = " + intersectionSPS1.getSize());
	System.out.println("Points = " + intersectionPoints1);

	System.out.println("Intersection 2:");
	System.out.println("Size = " + intersectionSPS2.getSize());
	System.out.println("Points = " + intersectionPoints2);
}

/**
 * Convert a single {@link SphericalPolygonsSet} boundary loop into a list
 * of {@link S2Point}'s.
 * 
 * @param loopStartVertex A {@link Vertex} within the boundary loop.
 * @return The equivalent list of {@link S2Point}'s.
 */
public static List<S2Point> getLoopPoints(Vertex loopStartVertex) {
	final List<S2Point> points = new ArrayList<S2Point>();
	Vertex currentVertex = loopStartVertex;
	do {
		points.add(currentVertex.getLocation());
		currentVertex = currentVertex.getOutgoing().getEnd();
	} while (loopStartVertex != currentVertex);
	return points;
}
```

Running the test prints the following:

```
Intersection 1:
Size = 1.6555645743210334E-12
Points = [S2Point{theta=0.017453292519943268, phi=1.5533430342749532}, S2Point{theta=0.017449225960259444, phi=1.553343033655835}, S2Point{theta=0.017453292519943292, phi=1.5533438485674156}]
Intersection 2:
Size = 3.0460968486245577E-4
Points = [S2Point{theta=0.017453292519943268, phi=1.5533430342749532}, S2Point{theta=0.0, phi=1.5533430342749524}, S2Point{theta=-1.8369701987210297E-16, phi=1.5707963267948966}, S2Point{theta=0.017453292519943295, phi=1.5707963267948968}]
```

Note that the 1st intersection is the result I was expecting, however the 2nd intersection resulted in a region that is almost exactly the same as the coordinates in `VERTICES2`. 

I have attached an image of the close-up between the two regions, and the intersection I am expecting, plotted on a map that supports the plotting of geodesic lines:

![HipparchusIntersectionBug](https://user-images.githubusercontent.com/104825346/183939722-817e7efa-716e-4646-bb67-8702a784c9be.png)

**Comment by wardev** [comment]
Definitely seems like a bug. Perhaps related to #49?

It could be helpful to add the intersection points to your plot so we can visualize the resulting polygons.

**Comment by JakeRandellOC** [comment]
Hmm I am not sure.

I have managed to simplify the coordinates a bit and drew up a diagram of where the coordinates are. Hopefully it is clear.

```
final static S2Point[] VERTICES1 = {	new S2Point(0.0193428339344826, 1.5537209444301618),
								new S2Point(0.0178197572212936, 1.553415699912148),
								new S2Point(0.01628496406053076, 1.5531081515279537),
								new S2Point(0.016284670226196844, 1.5531096373947835),
								new S2Point(0.019342540199680208, 1.5537224293848613), };

final static S2Point[] VERTICES2 = {	new S2Point(0.016, 1.555),
								new S2Point(0.017453292519943295, 1.555),
								new S2Point(0.017453292519943295, 1.5533430342749532),
								new S2Point(0.016, 1.5533430342749532),};
```

![HipparchusIntersectionBug2](https://user-images.githubusercontent.com/104825346/184613662-cc6e2139-d99e-44b9-a055-4d0ff9628851.png)

**Comment by maisonobe** [comment]
I think this is expected behavior linked to the hyperplane thickness.
When using your second set of coordinates, the problem appears when the hyperplane thickness used to build both spherical polygon sets is l4.96740427e-11 or larger, and it does not appear if this thickness 4.96740426e-11 or smaller. The intersection is probably within the thickness of the hyperplanes used to define the region.
I am afraid we cannot do more here. Specifying the hyperplanes thickness is difficult and depends on the use case.

**Comment by JakeRandellOC** [comment]
I realise I never got back to this issue, thank you both for taking the time to investigate the issue. I am satisfied with the explanation so I will close the issue.
