### ISSUE TITLE
Error with non-symmetric test in SequentialGaussNewtonOptimizer

### ISSUE THREAD

**Issue by robincourson1** [Hipparchus-Math/hipparchus#205]
Sending a symmetric matrix as a `Array2DRowRealMatrix` using `SequentialGaussNewtonOptimizer.WithAPrioriData(...)` triggers this warning :

`org.hipparchus.exception.MathIllegalArgumentException: matrice non symmétrique: la différence entre les éléments (0,1) et (1,0) est supérieure à 0`

The issue is triggered by [**CholeskyDecomposition**](https://github.com/Hipparchus-Math/hipparchus/blob/1f878485b46e61da7600398cd4edf28762995d8d/hipparchus-core/src/main/java/org/hipparchus/linear/CholeskyDecomposition.java#L52) (line 134) which does its own symmetry test. It appears not to be possible to change the tolerance margin with the call of `SequentialGaussNewtonOptimizer.WithAPrioriData(...)` since it does call `CholeskyDecomposition` without extra arguments.

Surprisingly, the identity matrix is not rejected, identity + 1e-9 is not rejected also, but identity +1e-8 is considered not symmetric (as well as others symmetric matrices...)

I'm using Hipparchus as part of the python wrapper for orekit but I'm not sure if it does make a difference. Testing the matrices using `MatrixUtils.isSymmetric(matrix, 1.0e-15)`  does return the correct test (why is `CholeskyDecomposition` not using this util function ?)

**Comment by BryanCazabonne** [comment]
Hi @robincourson1 

I had the same issue using Orekit. I generated an OPM file with an orbit determination and initialized a sequential least square estimation based on this OPM.

I'll fix the issue by adding a new signature for the method `withAPrioriData(...) ` allowing to initialize the Cholesky decomposition threshold.
