### ISSUE TITLE
Multiple Javadoc errors in code

### ISSUE THREAD

**Issue by VincentCucchietti** [Hipparchus-Math/hipparchus#215]
Hi everyone,

I'm opening this issue because I find several Javadoc errors when running the following command : ```mvn javadoc:javadoc -DskipTests```.

I'll try to fix them when I have some spare time.

Cheers,
Vincent

**Comment by maisonobe** [comment]
Could you try again with latest version from master branch?
I guess several errors have been fixed in the last few months, and the last ones were fixed as part of #272.

**Comment by VincentCucchietti** [comment]
Sure, wiil do @maisonobe  !

**Comment by VincentCucchietti** [comment]
Hi Luc, 

When generating javadoc with OpenJDK 20, there are a lots of warnings but no more errors :+1: .

Cheers,
Vincent
