### ISSUE TITLE
Add Field version of Erf class

### ISSUE THREAD

**Issue by VincentCucchietti** [Hipparchus-Math/hipparchus#218]
As straightforward as the title, it would be interesting to add the Field version of ```Erf```. 

I'll try to work on it ASAP.

**Comment by Serrof** [comment]
Hi Vincent,

given how Hipparchus works, one needs to know the derivatives of `erf` evaluated at the constant term and use the univariate composition.
To achieve the former, the easiest solution (both in terms of brain power and lines of code) is to use the method `integrate` on the exponential term related to `erf` and set the constant with the `double` version. A better option performance-wise is to work out the actual recursive relationship satisfied by the derivatives (which can then be validated by the first approach). Some quick calculations by hand gave me the following formula:
`f^(k+2) + 2 * (x * f^(k+1) + k* f^(k)) = 0` for `k>=0`
with  `f^(1) = (2/sqrt(pi)) * exp(-x * x)` and `f^(0)=erf(x)`

Cheers,
Romain.

**Comment by VincentCucchietti** [comment]
Closing this issue as merge request #219 was merged.
