### ISSUE TITLE
"Reset state" and "stop integration" capability for ODE step handlers

### ISSUE THREAD

**Issue by afossa** [Hipparchus-Math/hipparchus#220]
Following [this discussion](https://forum.orekit.org/t/provide-dostep-method-in-field-odeintegrator/2144?u=alberto), it would be interesting to add few features to the `(Field)ODEStepHandler` class which are similar to what is already provided by event handlers:

1. the `handleStep()` method should return an `Action` like `CONTINUE`, `STOP` and `RESET_STATE` rather than `void`
2. the event handler should implement a `resetState` method which is called when `RESET_STATE` is returned.

See the discussion on the forum for more details.

**Comment by maisonobe** [comment]
I am having a hard time trying to implement this as there are difficult interactions with events detection.
When an event occurs withing a step, all the step handlers are called first to handle the part before the event, then the event occurs, then all step handlers all called for the remaining part of the step. Of course, several events can occur within one step, so this behavior really occurs within a loop.

Now we want step handlers to also be able to reset states. So what should we do when the step handlers wants to reset a state but an event, computed with the state before the reset is triggered during this step?

The current behavior is already quite convoluted as it tries to handle properly cases where several events can occur at the exact same time, and also to handle properly cases where one even changes a state and this changes the behavior of upcoming events that may disappear or change occurrence time. Adding yet another reset here is difficult.

**Comment by afossa** [comment]
How do you currently handle two events that occur at exactly the same time? Which one is processes first?

If I have correctly understood, we will always be in a similar situation since each event defines a sub-step that goes from the beginning of the integrator step (or the previous event time) to the current event time, and step handlers are called within each of these sub-steps.

Now, if the state is reset according to the step handler action, the event may no longer exist, in which case the last sub-step becomes also meaningless. So I would process the event first, but I recognize it is in contrast with the current behavior.

**Comment by maisonobe** [comment]
I think simultaneous events are processed in the order of events detectors. This case might seem a corner case, but it does happen in real life, for example when the same detector is used for triggering two different things (think eclipses in space flight dynamics, where you want both to monitor battery charging and radiation pressure and both shut down at eclipse entry).

In your use case, do you reset the state all the time (i.e. at each step end) or only from time to time? What kind of change do you do to the state? Could your use case be reworked as an event detection with reset (event detectors can be triggered as many time as required, and even several time within a step)?

**Comment by afossa** [comment]
I have two use cases (for now at least):

In the first, the state is reset after each step. The state components are `DerivativeStructure` objects and the reset action keeps only their constant coefficient.
In the second, I do not reset the state but I stop the integration, and this of course happens only once (after possibly several steps)

I have already reworked the second with an event handler, implementing a "dummy" root finder that always does zero iterations since I am not interested in finding the exact time at which the zero crossing occurs, but just the step in which this happens.

For the first I haven't tried yet, but I think it will become too expensive even to just initialize a "dummy" root finder at each step, so I was looking for a more streamlined solution and an event handler with a reset option seemed the way to go for me.

**Comment by maisonobe** [comment]
What would you think about having a special event detector that has no `g` function but instead triggers at each step end?
Would that suit your needs, by adding a regular event handler to this detector?

**Comment by afossa** [comment]
Yes, I think it will do the job

**Comment by maisonobe** [comment]
In order to implement this, we need to implement #223 first.

**Comment by maisonobe** [comment]
New `{Field}ODEStepEndHandler` has been added to manage what should be done at end of each step.
There `stepEndOccurred` method can return an `Action` and if this action is `RESET_STATE` the state is reset between this step and next step.
Tell me if it suits your needs.
This involved *lots* of refactoring.

**Comment by afossa** [comment]
Thank you very much. It perfectly suits my use case.

There is only one problem: apparently the `{Field}ODEStepEndHandler#init()` method is not called at the beginning of the integration.

**Comment by maisonobe** [comment]
I think I have fixed the missing call to the `init` method, which by the had a wrong signature (it had a detector as third argument, but there are no detectors associated with step end handlers).

Does this work for you?

**Comment by afossa** [comment]
yes it is fixed now.
