### ISSUE TITLE
Add PCA class

### ISSUE THREAD

**Issue by paulk-asert** [Hipparchus-Math/hipparchus#221]
As per discussion on the forum:
https://forum.orekit.org/t/potential-principal-component-analysis-component/2175

**Comment by axkr** [comment]
Can we have a more general PCA implementation like in Mathematica, which also allows a `Method->"Correlation"` option, additional to the default `Method->"Covariance"`?
- https://reference.wolfram.com/language/ref/PrincipalComponents.html

**Comment by paulk-asert** [comment]
This is already supported. You need the constructor with additional options for scaling (correlation):
https://github.com/Hipparchus-Math/hipparchus/blob/master/hipparchus-stat/src/main/java/org/hipparchus/stat/projection/PCA.java#L76-L83

Using `new PCA(2)`  gives the equivalent* output in the Mathematica basic example.

Using `new PCA(3, true, true)` gives the equivalent* output as the example shown under "Options".

\* The absolute values are the same but the sign differs.
