### ISSUE TITLE
Issue with FastMath.expm1(709.85)

### ISSUE THREAD

**Issue by mmatsn** [Hipparchus-Math/hipparchus#228]
Hello,

org.hipparchus.util.FastMath.expm1(709.85) return -1.0,  while java.util.Math.expm1(709.85) return +Infinity.

Issue is present on Hipparchus 1.6 and 2.3.
Tested with OpenJDK 1.8

Code to reproduce issue:
`import org.hipparchus.util.FastMath;`
`public class ExpTest {`
`    public static void main(final String[] args) {`
`        System.out.println(System.getProperty("java.vm.name") + " " + System.getProperty("java.version"));`
`        final double val = 709.85;`
`        System.out.println("val=" + val + "  expm1: java=" + Math.expm1(val) + " hipp=" + FastMath.expm1(val));`
`    }`
`}`

I get :
OpenJDK 64-Bit Server VM 1.8.0_261
val=709.85  expm1: java=Infinity hipp=-1.0

**Comment by maisonobe** [comment]
Fixed in master branch.

Thanks for the report!
