### ISSUE TITLE
Matrix implementations of getEntry are slow

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#236]
I think [MATH-1654](https://issues.apache.org/jira/browse/MATH-1654) is also related to hipparchus.

At least in the internally implemented methods the `getEntry(i,j)` method should be replaced by a faster method.
IMO it doesn't make sense to check the indexes over and over again.

For example for calls of the method in the classes `Array2DRowFieldMatrix, Array2DRowRealMatrix`.

**Comment by maisonobe** [comment]
I agree, we can optimize this.

**Comment by maisonobe** [comment]
Fixed by PR #237
