### ISSUE TITLE
internal error while merging statistics

### ISSUE THREAD

**Issue by jhsenjaliya** [Hipparchus-Math/hipparchus#238]
I think the different Buffer level is causing this, 

some conditions I see that can end up having different level for dint
```
if (level > maxLevel) {
    maxLevel = level;
}
```

Actual error stack I get while doing the StreamingStatistics.aggregate()
```
Caused by: org.hipparchus.exception.MathIllegalStateException: internal error, please fill a bug report at {0}
	at org.hipparchus.stat.descriptive.rank.RandomPercentile$BufferMap.mergeUp(RandomPercentile.java:1063)
	at org.hipparchus.stat.descriptive.rank.RandomPercentile$BufferMap.absorb(RandomPercentile.java:1029)
	at org.hipparchus.stat.descriptive.rank.RandomPercentile.aggregate(RandomPercentile.java:1245)
	at org.hipparchus.stat.descriptive.StreamingStatistics.aggregate(StreamingStatistics.java:456)
	at .................<ommitted class/function name where this is called >...................
	... 15 common frames omitted
```

here is the code block responsible for this in mergeUp() function call:
basically its not able to find buffer that is not full in the list of all buffer from from `this` and `other`.

```
while ((first == null || second == null) && bufferIterator.hasNext()) {
                Buffer buffer = bufferIterator.next();
                if (!buffer.hasCapacity()) { // Skip not full buffers
                    if (first == null) {
                        first = buffer;
                    } else {
                        second = buffer;
                    }
                }
            }
            if (first == null || second == null || first.level > second.level) {
                throw new MathIllegalStateException(LocalizedCoreFormats.INTERNAL_ERROR);
            }
```

Pls let me know if you need any other info. Thanks

**Comment by jhsenjaliya** [comment]
@maisonobe , would be able to help look at this? i m hitting this frequently nowadays ( my data size is smaller like under 5k ).

**Comment by maisonobe** [comment]
I will try to have a look at this.
I am currently not at 100% capabilities due to a recent motorcycle accident, so I am slow at the keyboard with my left hand in a plaster cast, and I am left handed.

**Comment by jhsenjaliya** [comment]
Hi @maisonobe , sorry to hear that, pls take care, hope u get well soon !

**Comment by maisonobe** [comment]
I have looked at this and did not find any obvious error by simply reading the code.
Could you provide us a standalone test case along with data to reproduce the bug?

**Comment by jhsenjaliya** [comment]
sure, i will try to create one.
problem I saw was that, all buffers in bufferMap from registry has capacity ( next < size ) so none got assigned to `first` or `second` so it throws the error. 
btw, this line I dont understand, `if (!buffer.hasCapacity())` why is that only buffer that dont have any capacity (its full) will be assigned to first and second ( is it assumed that there will be only 2 such buffer ) ?

**Comment by maisonobe** [comment]
I guess the method was intended to be called only when merging is necessary to free up one buffer.
As long as there is still room, merging should not be necessary, and hence should not be done to preserve accuracy of the quantiles estimates.

**Comment by maisonobe** [comment]
I hope to have fixed this in the master branch.
Could you please check if you get sensible results with the fix?
Beware that RandomPercentile statistics are not always accurate as they involve randomly dropping some data when capacity is exceeded.
