### ISSUE TITLE
matrixExponential giving NaN results

### ISSUE THREAD

**Issue by mgrutten** [Hipparchus-Math/hipparchus#239]
I am getting NaN results for a matrix exponential on a matrix with a large norm.
This is completely my fault ... I contributed the code a few years ago.

**Comment by Serrof** [comment]
Hi Mark. Do you have a reproductible example so that somebody else could try working on it or do you think you'll have time to tackle that yourself?

**Comment by mgrutten** [comment]
Hey Romain!  Apologies ... I made a corresponding pull request [here](https://github.com/Hipparchus-Math/hipparchus/pull/240), but never closed off this issue.  I added an example to the testing code that exercises the problem case I had.
