### ISSUE TITLE
Deprecated versions of CI actions

### ISSUE THREAD

**Issue by sdinot** [Hipparchus-Math/hipparchus#241]
When the Github action pipeline is run, several warnings are raised because of deprecated versions of CI actions are used:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
>
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by sdinot** [comment]
@maisonobe, this issue can be closed as PR #242 was merged and resolves it.

**Comment by maisonobe** [comment]
Thanks, I forgot to close it.
