### ISSUE TITLE
Define own `compareTo` method in `IndexedEigenvalue` class

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#248]
Can we somehow define our own `compareTo` method in `IndexedEigenvalue` class?
https://github.com/Hipparchus-Math/hipparchus/blob/ea873ba0df8c7a3705f251a27711ac4696aae84b/hipparchus-core/src/main/java/org/hipparchus/linear/OrderedComplexEigenDecomposition.java#L139-L146

For example as:
```java
        @Override
        public int compareTo(final IndexedEigenvalue other) {
            return Double.compare(other.eigenValue.norm(), eigenValue.norm());
        }
```

as required in 
- https://github.com/axkr/symja_android_library/issues/718

**Comment by maisonobe** [comment]
It seems to break the Riccati equation solver which needs ordered eigen values in some order.

**Comment by maisonobe** [comment]
Would the following patch suit your needs?
It allows defining a different ordering but preserves the existing default that works for Riccati solver.
[issue-248.txt](https://github.com/Hipparchus-Math/hipparchus/files/11272579/issue-248.txt)

**Comment by axkr** [comment]
> Would the following patch suit your needs?
> It allows defining a different ordering but preserves the existing default that works for Riccati solver.

Yes I think if we have a `Comparator<Complex>`we can define for the ordering that should work

**Comment by axkr** [comment]
```
Array2DRowRealMatrix{{1.0,0.0,0.0},{-2.0,1.0,0.0},{0.0,0.0,1.0}}
```

throws an NPE

```java
java.lang.NullPointerException: null
	at org.hipparchus.linear.AbstractFieldMatrix.setColumnVector(AbstractFieldMatrix.java:566) ~[classes/:?]
	at org.hipparchus.linear.ComplexEigenDecomposition.<init>(ComplexEigenDecomposition.java:143) ~[classes/:?]
	at org.hipparchus.linear.OrderedComplexEigenDecomposition.<init>(OrderedComplexEigenDecomposition.java:98) ~[classes/:?]
```

**Comment by maisonobe** [comment]
The NPE seems to not be due to the change, but to have always existed.
The characteristic polynomial of this matrix is (1-λ)³, so the matrix has a single eigen value λ=1. For this eigen value, there are two eigen vectors: v₁ = (0, 1, 0) and v₂ = (0, 0, 1). The NPE occurs when we attempt to find a third eigen vector which does not exist.

You have found a new bug!

**Comment by axkr** [comment]
> You have found a new bug!

So should I create new issue?
