### ISSUE TITLE
NullPointerException in OrderedComplexEigenDecomposition

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#249]
Follow up from #248:

Thanks for the change, which works for most cases, but this case for `matrix`

```java
Array2DRowRealMatrix{{1.0,0.0,0.0},{-2.0,1.0,0.0},{0.0,0.0,1.0}}
```

and the following call:

```java
ComplexEigenDecomposition ced = new OrderedComplexEigenDecomposition(matrix, //
          ComplexEigenDecomposition.DEFAULT_EIGENVECTORS_EQUALITY, //
          ComplexEigenDecomposition.DEFAULT_EPSILON, //
          ComplexEigenDecomposition.DEFAULT_EPSILON_AV_VD_CHECK, //
          (c1, c2) -> Double.compare(c2.norm(), c1.norm()));
```

throws a NullPointerException

```
java.lang.NullPointerException: null
	at org.hipparchus.linear.AbstractFieldMatrix.setColumnVector(AbstractFieldMatrix.java:566) ~[classes/:?]
	at org.hipparchus.linear.ComplexEigenDecomposition.<init>(ComplexEigenDecomposition.java:143) ~[classes/:?]
	at org.hipparchus.linear.OrderedComplexEigenDecomposition.<init>(OrderedComplexEigenDecomposition.java:98) ~[classes/:?]
```

The eigenvectors contain a `null`value at line `ComplexEigenDecomposition.java:143`
![image](https://user-images.githubusercontent.com/3109793/233239496-bfcd5d17-6a8f-4ff4-ab84-e6fc97991e07.png)

I would have expected a 0-vector `{0.0,0.0,0.0}` instead of the `null` value.

**Comment by axkr** [comment]
We want to implement the MMA behavior; how can we do it, if hipparchus triggers an exception?
![image](https://user-images.githubusercontent.com/3109793/233605574-45ec031a-49fb-4eb6-82c6-14bdaa6c0da4.png)

https://reference.wolfram.com/language/ref/Eigenvectors.html

**Comment by maisonobe** [comment]
OK, then I'll add the zeros, with some documentation.
It nevertheless looks strange to me as [Wolfram Alpha](https://www.wolframalpha.com/input?i=eigenvectors+%7B%7B1%2C0%2C0%7D%2C%7B-2%2C1%2C0%7D%2C%7B0%2C0%2C1%7D%7D) really returns two eigenvectors for this matrix.

**Comment by axkr** [comment]
Yes there are some "conventions" described in the reference for symbolic and numerical evaluations.

The first 2 examples are symbolic evaluations the last 2 are numerical:
![image](https://user-images.githubusercontent.com/3109793/233617570-c3349365-9670-4726-a2d8-e72d281dc0c6.png)
