### ISSUE TITLE
Calculation determinant in class EigenDecomposition

### ISSUE THREAD

**Issue by parnold-x** [Hipparchus-Math/hipparchus#262]
The calculation seems to neglect the imaginary parts of the eigenvalues
For
![image](https://github.com/Hipparchus-Math/hipparchus/assets/3041711/4ad62d39-f148-431c-b894-7d1aeb2e465e)

The result is -2.25 but it should be -3

**Comment by maisonobe** [comment]
This was weird!

Thanks for the report, it is now hopefully fixed in master branch.
