### ISSUE TITLE
Implement Comparable for UnivariateDerivative

### ISSUE THREAD

**Issue by Serrof** [Hipparchus-Math/hipparchus#275]
In line with #274 and also [discussions on the forum](https://forum.orekit.org/t/error-when-evaluating-field-linear-splines/2545)

**Comment by Serrof** [comment]
Cannot do `FieldUnivariateDerivative ` yet as it would require all `CalculusFieldElement` to already implement `Comparable`

**Comment by Serrof** [comment]
@maisonobe `UnivariateDerivative` has `implements Derivative<T>, CalculusFieldElement<T>` but the latter is redundant w.r.t. the former, can I remove it?

**Comment by maisonobe** [comment]
Yes, I think you can remove redundant declarations.
Beware that we are very close to release 3.0, Bryan is working on it.
