### ISSUE TITLE
OpenIntToDoubleHashMap; OpenIntToFieldHashMap implement Serializable but have no hashCode() and equals() method

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#289]
`org.hipparchus.util.OpenIntToDoubleHashMap`and
`org.hipparchus.util.OpenIntToFieldHashMap` 
define `Serializable` interface but no `hashCode()` and `equals()` method.

See:
- https://github.com/Hipparchus-Math/hipparchus/blob/f1948e10f100a5380c869c76b4f0e8f5f1004b68/hipparchus-core/src/main/java/org/hipparchus/util/OpenIntToFieldHashMap.java#L44
- https://github.com/Hipparchus-Math/hipparchus/blob/f1948e10f100a5380c869c76b4f0e8f5f1004b68/hipparchus-core/src/main/java/org/hipparchus/util/OpenIntToDoubleHashMap.java#L40

There must be an overriden `equals()` and `hashCode()` method so they will return true if deserialized instances of the same original object are compared.

**Comment by axkr** [comment]
The attribute `private final Field<T> field;` must be made `Serializable`.
Otherwise `OpenIntToFieldHashMap` can't be `Serializable.

Is this intended or should the `Serializable` interface be removed from `OpenIntToFieldHashMap` ?

**Comment by Serrof** [comment]
Hi @axkr,
Would you be able to create a fix for this?
Cheers

**Comment by maisonobe** [comment]
I will do it for `OpenIntToDoubleHashMap`, but I guess having `OpenIntToFieldHashMap` implement `Serializable` is an error. Field elements are not serializable.
I also think more and more than serialization is not really a good thing and should be removed altogether.
