### ISSUE TITLE
Add constrained optimization

### ISSUE THREAD

**Issue by maisonobe** [Hipparchus-Math/hipparchus#296]
As part of a thread about [Powel optimizer](https://forum.orekit.org/t/how-to-define-constraints-for-the-powelloptimizer/2912/4), one participant proposed to contribute constrained optimization features, which is something we wanted to have in Hipparchus for years!

So this issue is opened as a reference to handle this contribution.

**Comment by maisonobe** [comment]
A first version of the contribution has been added to the master branch.
It works but triggers many warnings in the continuous integration process (see [SonarQuve code smells](https://sonar.orekit.org/project/issues?id=org.hipparchus%3Ahipparchus-aggregator&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL).

Basically, it lacks testing and javadoc. I have fixed a number of javadoc failures (initially, there were more than 500 warnings), but clearly not all.

Could someone take over at this stage and help fix things, adding missing javadoc, replacing TBD in Javadoc with proper description and greatly improving test coverage?

Once SonarQube is back to green, we can think about refactoring some parts and improving performances.

**Comment by Serrof** [comment]
I don't want this to postpone the next minor release (which we need soonish for Orekit), so I'll open an MR for coverage.

**Comment by Serrof** [comment]
InequalityConstraintSet is never used and implements an empty interface (OptimizationData). I do not understand its purpose. @roccafrancesco

**Comment by roccafrancesco** [comment]
Hello Serrof
if the optimization problem is always formulated in the standard form (g(x)<0, h(x)=0) it has no use. 
In the case, however, you want to leave more freedom in the construction of the problem and use a number of functions greater than one for each type of costraint, maybe because functions could provide the gradient in different manner(analytical, autodifferentiation, blackbox)  g1(x).......gn(x),h1(x)....hm (x) ,would have the purpose to compose this functions in the standard form,accepted by the various algorithms.@Serrof

**Comment by Serrof** [comment]
Thanks for the quick reply. But it's missing getters no? The arguments passed to the constructor cannot be called back at the moment. And to be honest, if there is no test using it, this is "dead" code and should probably not be kept in Hipparchus.

**Comment by roccafrancesco** [comment]
All right. if you don't think it is useful it can be removed now and possibly implemented at a later@Serrof

**Comment by Serrof** [comment]
Alright, coverage is almost green, just a bit short on conditions (see [here](https://sonar.orekit.org/dashboard?id=org.hipparchus%3Ahipparchus-aggregator)). I think ADMMQPOptimizer is a good target to boost the numbers, so I'll open a pull request for that.

**Comment by Serrof** [comment]
Still under 90%. I'll add more tests, maybe not just on the new optimization stuff actually

**Comment by roccafrancesco** [comment]
HI
it is not possible to use these methods by assigning any parameters. The implemented papers, in fact, use specific parameters and apply them to all set of problems. The ideal would be to use the same benchmarks used by optimizers developed in other programming languages.

**Comment by Serrof** [comment]
The recent sonarqube reset means we're ok for coverage. So what are we still missing @maisonobe? Javadoc?
