### ISSUE TITLE
Improvable performance in Gradient

### ISSUE THREAD

**Issue by Serrof** [Hipparchus-Math/hipparchus#302]
Algebraic operations and intrinsic fuctions spend a non-negligigle time copying arrays

This should be avoided, especially since the class is used extensively in Orekit

**Comment by maisonobe** [comment]
Good job Romain!

**Comment by MaximeJo** [comment]
Great job indeed @Serrof !!

**Comment by Serrof** [comment]
Cheers, but the profiler did the job ;)
