### ISSUE TITLE
Rotation.getAngles(ZYX, VECTOR_OPERATOR) inconsistent in 'Gimbal Lock'

### ISSUE THREAD

**Issue by HannesWell** [Hipparchus-Math/hipparchus#304]
When calling `Rotation.getAngles(ZYX, VECTOR_OPERATOR)` for a `org.hipparchus.geometry.euclidean.threed.Rotation` the result is inconsistent (and probably wrong) if the rotation is in the ['Gimbal Lock'](https://en.wikipedia.org/wiki/Gimbal_lock), i.e. the rotation around the Y axis has an angle of `+-PI/2` leading to a singularity.

For the `originalMatrix` in the following example the computed angles are `0, PI/2, 0`  (case rotation 1). But if one creates a rotation using those angles with the same rotation convention and order the resulting rotation-matrix is different from the `originalMatrix` (and not only marginally due to some rounding/discretization errors) (case rotation 2).
Only when using the angles `0, PI/2, PI/2` the resulting rotation-matrix is equal to the `originalMatrix` (ignoring rounding/discretization errors)(case rotation 3).

Interestingly if one uses the rotation-matrix of a rotation created with angles `0, PI/2, PI/2` (which is almost equal to the `originalMatrix` but slightly off due to rounding/discretization errors), creates a new rotation from it and then call `getAngles(ZYX, VECTOR_OPERATOR)` on that, the returned angles are effectively `0, PI/2, PI/2` (case rotation 4).

When debugging/comparing that last case it showed that the reason for the difference that atan2 is called with arguments `0,0` in the 'exact' matrix case while it is called with `2.2E-16, 0` in the case of the computed, slightly off matrix.
But the atan2 function seem to be non steady around the zero and returned `0` in the former case and `PI/2` in the latter.

Do you think it would be possible to make the angles computation more robust when close to or exactly in the Gimbal lock respectively e.g. by handling the case differently if atan2 would be called with `0,0`?
I haven't checked the other conventions but they are maybe affected as well.

With Hipparchus 2 we catched the exception in case of singularities ('Gimbal Lock') and used a special handling fitted to ZYX convention. AFAICT it worked well.

I'm currently looking into how it would fit best into Hipparchus' Rotation class and would then be glad to share it. It just not trivial since that handling was based on the entries of a rotation-matrix, while the Rotation class uses Quaternions internally and I think a solution should then be adapted accordingly.

```
	public static void main(String[] args) {
		double[][] originalMatrix = { //
			{ 0.0, 1.0, 0.0 }, //
			{ 0.0, 0.0, -1.0 }, //
			{ -1.0, 0.0, 0.0 } //
		};
		{
			System.out.println("Rotation 1");
			Rotation rotation = new Rotation(originalMatrix, 1.0e-10);
			double[] angles = rotation.getAngles(ZYX, VECTOR_OPERATOR);
			printArray(angles);
		}
		{
			System.out.println("Rotation 2");
			Rotation rotation = new Rotation(ZYX, VECTOR_OPERATOR, 0, FastMath.PI / 2, 0);
			double[][] matrix = rotation.getMatrix();
			printMatrix(matrix);
		}
		{
			System.out.println("Rotation 3");
			Rotation rotation = new Rotation(ZYX, VECTOR_OPERATOR, 0, FastMath.PI / 2, FastMath.PI / 2);
			double[][] matrix = rotation.getMatrix();
			printMatrix(matrix);
		}
		{
			System.out.println("Rotation 4");
			Rotation rotation = new Rotation(ZYX, VECTOR_OPERATOR, 0, FastMath.PI / 2, FastMath.PI / 2);
			double[][] matrix = rotation.getMatrix();
			printMatrix(matrix);

			double[] angles = new Rotation(matrix, 1.0e-10).getAngles(ZYX, VECTOR_OPERATOR);
			printArray(angles);
		}
	}

	private static void printArray(double[] angles) {
		System.out.println(Arrays.toString(angles));
		System.out.println();
	}

	private static void printMatrix(double[][] matrix) {
		for (double[] row : matrix) {
			System.out.println(Arrays.toString(row));
		}
		System.out.println();
	}
```
which prints
```
Rotation 1
[0.0, 1.5707963267948966, 0.0]

Rotation 2
[2.220446049250313E-16, 0.0, 1.0]
[-0.0, 1.0, 0.0]
[-1.0, -0.0, 2.220446049250313E-16]

Rotation 3
[2.220446049250313E-16, 1.0, 2.220446049250313E-16]
[0.0, 2.220446049250313E-16, -1.0]
[-1.0, 2.220446049250313E-16, 0.0]

Rotation 4
[2.220446049250313E-16, 1.0, 2.220446049250313E-16]
[0.0, 2.220446049250313E-16, -1.0]
[-1.0, 2.220446049250313E-16, 0.0]

[0.0, 1.5707963267948963, 1.5707963267948966]
```

**Comment by maisonobe** [comment]
Hi @HannesWell thanks for the analysis.
I am not sure what to do about this. In fact, as gimbal lock *is* a singularity, it is prone to problems when numerical noise is introduced. The `atan2` method works properly in my humble opinion. There is a convention for atan(0,0), and the numerical truth for `atan2(y,0)` is sign(y)*π/2. I agree 2.2e-16 is close to zero, but it is positive. In fact we would also get π/2 with atan2(1.0e-300, 0) (I checked, it works).
So we cannot change `FastMath.atan2`, but perhaps we could set up a special function devoted to `Rotation`, in the same spirit we already have a `safeAsin` and `safeAcos` that have been set up to work around other singularities.

**Comment by HannesWell** [comment]
> I am not sure what to do about this. In fact, as gimbal lock _is_ a singularity, it is prone to problems when numerical noise is introduced. The `atan2` method works properly in my humble opinion. There is a convention for atan(0,0), and the numerical truth for `atan2(y,0)` is sign(y)*π/2. I agree 2.2e-16 is close to zero, but it is positive. In fact we would also get π/2 with atan2(1.0e-300, 0) (I checked, it works).

The singularity is indeed difficult and yes the atan2 function itself is fine.
My initial text was probably a bit mislead, but the problem here is actually that in the specific case I mentioned that `atan2(0,0)` is called to calculate `angles[2]`, which leads to `angles[2]=0` while the correct value would be (in this specific case) `PI/2`. Therefore the rotations that have a little noise return a correct result (with a some noise), while the rotation with exact values returns false result.

> So we cannot change `FastMath.atan2`, but perhaps we could set up a special function devoted to `Rotation`, in the same spirit we already have a `safeAsin` and `safeAcos` that have been set up to work around other singularities.

Yes I was thinking about that as well and as far as I can tell, at least for the specific case mentioned above that special method should return PI/2 if both atan2 arguments are zero. But I would have to check if this is generally applicable.
I have to admit I'm more with rotation matrices and not so much with Quaternion.

For the case `getAngles(RotationOrder.ZYX, RotationConvention.VECTOR_OPERATOR)` I have now implemented the following alternative that is based on extracting the angles from the corresponding rotation matrix. The resulting angles are different, mainly because I chose `phi=0` arbitrarily while the current Rotation implementation seems to prefer `psi=0` (in the Gimbal lock only the sum/difference of `phi` and `psi` is relevant with this convention, so either `phi` or `psi` can be choosen freely), but still describe the same rotation (but rotation-angles are in general no unambiguous).
The rotation matrix for the z-y′-x″ intrinsic rotation convention (which should correspond to `RotationOrder.ZYX, RotationConvention.VECTOR_OPERATOR)`) is depicted in:
https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions#Euler_angles_(z-y%E2%80%B2-x%E2%80%B3_intrinsic)_%E2%86%92_rotation_matrix

When comparing the entries one can calculate:
```
private static double[] computeAngles(Rotation rotation) {
	double[][] rotationMatrix = rotation.getMatrix();
	// Assume rotation matrix is orthogonal and has determinant +1
	double thetaRad; // result is in interval [-pi/2,pi/2]
	double e20 = rotationMatrix[2][0];
	if (e20 <= -1) { // due to discretization errors the result can be slightly above/below +-1
		thetaRad = FastMath.PI / 2;
	} else if (e20 >= +1) {
		thetaRad = -(FastMath.PI / 2);
	} else {
		thetaRad = FastMath.asin(-e20);
	}
	double phiRad, psiRad;
	// In all cases below the arguments of atan2 cannot both be zero at the same time.
	if (!isZero(FastMath.abs(e20) - 1)) { // cos(theta)>=0 because theta is in [-pi/2,pi/2]
		psiRad = FastMath.atan2(rotationMatrix[1][0], rotationMatrix[0][0]);
		phiRad = FastMath.atan2(rotationMatrix[2][1], rotationMatrix[2][2]);
	} else {
		// cos(theta) is (approximately) zero -> (straight 'up' or 'down'), Gimbal-Lock.
		// -> the angles phi and psi both rotate around z axis.
		phiRad = 0.0; // only the combination of both angles is relevant. Arbitrarily set phi to fixed zero
		psiRad = FastMath.atan2(-rotationMatrix[0][1], rotationMatrix[1][1]);
		// second summand of used entries is zero (contains factor sin(0)) in rotation matrix
	}
	return new double[] { phiRad, thetaRad, psiRad };
}
```
This code was originally written for a transformation-matrix. In order to avoid the intermediate build of the rotation matrix I inlined it and got the following equivalent code:
```
private double[] computeAngles(Rotation rotation) {
	double q0 = rotation.getQ0();
	double q1 = rotation.getQ1();
	double q2 = rotation.getQ2();
	double q3 = rotation.getQ3();
	// Assume rotation matrix is orthogonal and has determinant +1
	double thetaRad; // result is in interval [-pi/2,pi/2]
	double e20 = 2.0 * (q1 * q3 + (q0 * q2));
	if (e20 <= -1) { // due to discretization errors the result can be slightly above/below +-1
		thetaRad = FastMath.PI / 2;
	} else if (e20 >= +1) {
		thetaRad = -(FastMath.PI / 2);
	} else {
		thetaRad = FastMath.asin(-e20);
	}
	double phiRad, psiRad;
	// In all cases below the arguments of atan2 cannot both be zero at the same time.
	if (!isZero(FastMath.abs(e20) - 1)) { // cos(theta)>=0 because theta is in [-pi/2,pi/2]
		psiRad = FastMath.atan2(2.0 * (q1 * q2 - (q0 * q3)), 2.0 * (q0 * q0 + (q1 * q1)) - 1.0);
		phiRad = FastMath.atan2(2.0 * (q2 * q3 - (q0 * q1)), 2.0 * (q0 * q0 + (q3 * q3)) - 1.0);
	} else {
		// cos(theta) is (approximately) zero -> (straight 'up' or 'down'), Gimbal-Lock.
		// -> the angles phi and psi both rotate around z axis.
		phiRad = 0.0; // only the combination of both angles is relevant. Arbitrarily set phi to fixed zero
		psiRad = FastMath.atan2(-2.0 * (q1 * q2 + (q0 * q3)), 2.0 * (q0 * q0 + (q2 * q2)) - 1.0);
		// second summand of used entries is zero (contains factor sin(0)) in rotation matrix
	}
	return new double[] { phiRad, thetaRad, psiRad };
}
```
Maybe it is possible to simplify this further, but I would have to think about that a little bit more.

I might be wrong, but as far as I can tell using this approach atan2 would never be called with both arguements zero due to the nature of the problem and testing this with many different exact perpendicular angles and some with noice this all seems to work well.

But I don't want to (and cannot do with absolute confidence) recommend any approach over the other, I mainly wanted to show this alternative, maybe it is interesting for you and we come to a more robust solution.
Applying a similar approach to all other conventions would also be more work and some porperties could also be different.

**Comment by maisonobe** [comment]
Please check if the fix works for you.
I have attempted to make this really generic and reduce the huge number of cases: 12 rotation orders, times two rotations conventions, times three paths (regular, first singularity, second singularity), times two types (primitive doubles and fields).
