### ISSUE TITLE
Introduce Mockito as test dependency 

### ISSUE THREAD

**Issue by Serrof** [Hipparchus-Math/hipparchus#321]

**Comment by Serrof** [comment]
Ok so I thought I did add Mockito as a test dependecy, but my IDE doesn't manage to import. @maisonobe any idea on what I did wrong?

**Comment by VincentCucchietti** [comment]
Hi Serrof,

You want me to take a look ? 

Cheers,
Vincent

**Comment by Serrof** [comment]
That would be great thanks

**Comment by VincentCucchietti** [comment]
Hi @Serrof ,

It is working on my end @Serrof, i suggest you to reload all your maven projects so that the dependency to mockito is downloaded and visible to your IDE.

Cheers,
Vincent
