### ISSUE TITLE
Make JacobiKey public in PolynomialsUtils

### ISSUE THREAD

**Issue by MaximeJo** [Hipparchus-Math/hipparchus#322]
[JacobiKey](https://github.com/Hipparchus-Math/hipparchus/blob/6a43f8559814f3e52cf936d36eeb87a5770bd02f/hipparchus-core/src/main/java/org/hipparchus/analysis/polynomials/PolynomialsUtils.java#L270) is a private inner class of `PolynomialsUtils` class.

I suggest to make it public or extract it in a dedicated class, so that it can be used elsewhere.

See for example [this usage](https://gitlab.orekit.org/orekit/orekit/-/blob/develop/src/main/java/org/orekit/propagation/semianalytical/dsst/utilities/JacobiPolynomials.java?ref_type=heads#L172) in Orekit where the class had to be duplicated.

**Comment by maisonobe** [comment]
A dedicated class seems appropriate.
