### ISSUE TITLE
In LogNormalDistribution.java, it appears shape & scale are reversed/mis-labelled.

### ISSUE THREAD

**Issue by oleersoy** [Hipparchus-Math/hipparchus#4]
Assuming this affects hipparchus as well:
https://issues.apache.org/jira/browse/MATH-1373

**Comment by netomi** [comment]
A quick look shows that the calculations are correct, but the parameters are ill-defined:

* m is the <em>scale</em> parameter: this is the mean of the normally distributed natural logarithm of this distribution
* s is the <em>shape</em> parameter: this is the standard deviation of the normally distributed natural logarithm of this distribution.

while it should be:

* m -> location parameter
* s -> scale parameter
