### ISSUE TITLE
BisectionSolver should throw an exception, if no solution is available in the interval

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#40]
This is related to https://github.com/axkr/symja_android_library/issues/60

This snippet returns `4.999999701976776` for the BisectionSolver
```
	public void testBisection() {
		BisectionSolver solver = new BisectionSolver();
		System.out.println(solver.solve(100, x->Math.cos(x)+2, 0.0, 5.0));
	}
```

The other solvers throw an exception, if there's no solution.

**Comment by maisonobe** [comment]
Thanks for the report.
The bug should be solved now, it is in the master branch.
