### ISSUE TITLE
StorelessUnivariateStatistic should extend DoubleConsumer

### ISSUE THREAD

**Issue by netomi** [Hipparchus-Math/hipparchus#5]
Any storeless univariate statistic should extend from DoubleConsumer. The `accept(double)` method should be delegated to `increment(double)`.

**Comment by psteitz** [comment]
+1
Probably the simplest way to enable this is to have AbstractStorelessUnivariateStatistic implement DoubleConsumer in this way.

**Comment by netomi** [comment]
StorelessUnivariateStatistic as well as DescriptiveStatistics and StreamingStatistics now extend from DoubleConsumer. Added separate test cases for each class.
