### ISSUE TITLE
Broken links: Interpolation 

### ISSUE THREAD

**Issue by hmf** [Hipparchus-Math/hipparchus#53]
In the page:

https://www.hipparchus.org/hipparchus-core/analysis.html#Interpolation

The following two links are broken: 

https://www.hipparchus.org/apidocs/org/hipparchus/analysis/interpolation/BicubicSplineInterpolator.html
https://www.hipparchus.org/apidocs/org/hipparchus/analysis/interpolation/BicubicSplineInterpolatingFunction.html

The API Documentation:

https://hipparchus.org/apidocs/org/hipparchus/analysis/interpolation/UnivariateInterpolator.html

does not show Bicubic. 

Their is also a mention of "Microsphere" interpolator but no links to the class/implementation API. 

HTHS

**Comment by maisonobe** [comment]
This should be fixed in the master branch of the git repository.
The fact UnivariateInterpolator does not show bicubic is notmal, they are bivariate interpolators.

Thanks for the report!
