### ISSUE TITLE
ExponentialDistribution CDF definition?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#59]
From the CDF definition at:
- https://en.wikipedia.org/wiki/Exponential_distribution

should line 100
- https://github.com/Hipparchus-Math/hipparchus/blob/ae239317bbc9e268d0db5ae72a4ba3a581a1492c/hipparchus-core/src/main/java/org/hipparchus/distribution/continuous/ExponentialDistribution.java#L100

be

```
ret = 1.0 - FastMath.exp(-x * mean);
```

and line 119
- https://github.com/Hipparchus-Math/hipparchus/blob/ae239317bbc9e268d0db5ae72a4ba3a581a1492c/hipparchus-core/src/main/java/org/hipparchus/distribution/continuous/ExponentialDistribution.java#L119

be

```
ret = -1/mean * FastMath.log(1.0 - p);
```

?

**Comment by maisonobe** [comment]
I don't think so.
The distribution is constructed from the mean itself, and the λ parameter in the wikipedia page is the reciprocal of the mean. The unit tests have been checked against R.
