### ISSUE TITLE
GumbelDistribution definition?

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#60]
The javadoc references for the Gumbel distribution CDF, PDF seem to be different:
- https://en.wikipedia.org/wiki/Gumbel_distribution 
- http://mathworld.wolfram.com/GumbelDistribution.html

Wolfram defines the CDF different from implementation:

```
    final double z = (x  - mu) / beta;
    return 1.0 - FastMath.exp(-FastMath.exp(z));
```

Can you clarify which definitions are used in the GumbelDistribution class?

**Comment by maisonobe** [comment]
I think we use the same notation as the wikipedia page, which means the implementation refers to the Gumbel distribution for maximum values. The MathWorld page on the other hand refers to the Gumbel distribution for minimum values. Using one convention or the other corresponds to changing the sign of the x values.
