### ISSUE TITLE
Feature Request: Add Fraction#signum()

### ISSUE THREAD

**Issue by lorenzleutgeb** [Hipparchus-Math/hipparchus#63]
I am using `org.hipparchus.Fraction` and would like to know whether a specific object of this class represents a negative number or not. Of course I know that I could just get the nominator and the denominator, and compute the exclusive or of whether they are negative. But that's cumbersome and I feel that Hipparchus should do this job for me. I therefore request the addition of `org.hipparchus.Fraction#signum()` with semantics similar to those of [`java.math.BigInteger#signum()`](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/math/BigInteger.html#signum()).

My current implementation is:

```java
public static int signum(Fraction fraction) {
  return
    Integer.signum(fraction.getNumerator()) *
    Integer.signum(fraction.getDenominator());
}
```

It seems to be the case that Hipparchus uses the numerator to store the sign, so maybe it would be enough to just get its signum, but I did not want to rely on its internals.

I am happy to provide a PR upon request.

**Comment by maisonobe** [comment]
I confirm the sign is always stored in the numerator, so it was indeed sufficient to check it.

I have add the feature in the master branch, for both Fraction and BigFraction.

Thanks for the report!

**Comment by lorenzleutgeb** [comment]
Thank you for addressing my feature request so promptly!
