### ISSUE TITLE
Add link to Orkit Discourse forums in website

### ISSUE THREAD

**Issue by hmf** [Hipparchus-Math/hipparchus#89]
Did not see a "documentation" project, so I am placing this request here. If need be I can do it elsewhere. 

Could you add a link to the forums under some common title such as *community*?
I may have missed it but it should easy to see. Please place it in a prominent location.
Make sure one need not scroll to see it.

HTHs.

**Comment by maisonobe** [comment]
There was already a forum entry in the menu, but I have added a paragraph in
the main page and links in the footers.
The site will be updated this afternoon (European time)

**Comment by maisonobe** [comment]
The site has been updated online. It corresponds to the state of the master branch as of 2020-05-05.
