### ISSUE TITLE
Complex utility functions if imaginary part is 0

### ISSUE THREAD

**Issue by axkr** [Hipparchus-Math/hipparchus#92]
Are there some similar utility functions for the `Complex` number type as in the Guava `DoubleMath` utility class, if the imaginary part is `0.0`?

`isMathematicalInteger`
https://github.com/google/guava/blob/45958948bea8f7aaf38c1a3dd200ce0263c0bcfa/android/guava/src/com/google/common/math/DoubleMath.java#L286

`roundToInt`:
https://github.com/google/guava/blob/45958948bea8f7aaf38c1a3dd200ce0263c0bcfa/android/guava/src/com/google/common/math/DoubleMath.java#L131

**Comment by maisonobe** [comment]
For questions, please use the new forum at https://forum.orekit.org/c/hipparchus-usage/.

There are not (yet) similar functions in Complex. We have added quite a large number of functions so `Complex` now implements the new `CalculusFieldElement` interface, for the sake of solving issue #67. The closest function to your second need would be `round`, but it is in the `RealFieldElement` interface, not in the `CalculusFieldElement` class. We could move it up as explained in the comment I wrote [here](https://github.com/Hipparchus-Math/hipparchus/issues/67#issuecomment-630633201).

We could implement the first method directly in `Complex`, without reference to any higher level interface.
