### ISSUE TITLE
Add mathematical functions with a RealFieldElement argument

### ISSUE THREAD

**Issue by BryanCazabonne** [Hipparchus-Math/hipparchus#95]
Currently, `FieldGradient`, `FieldUnivariateDerivative1` and `FieldUnivariateDerivative2` classes have 2 kind of mathematical methods. On the one hand, the ones with a double value argument and, the other hand, the ones with their object type in argument. See the example below for `FieldGradient` class:

    /** {@inheritDoc} */
    @Override
    public FieldGradient<T> multiply(final double a) {
        final FieldGradient<T> result = newInstance(value.multiply(a));
        for (int i = 0; i < grad.length; ++i) {
            result.grad[i] = grad[i].multiply(a);
        }
        return result;
    }

    /** {@inheritDoc} */
    @Override
    public FieldGradient<T> multiply(final FieldGradient<T> a) {
        final FieldGradient<T> result = newInstance(value.multiply(a.value));
        for (int i = 0; i < grad.length; ++i) {
            result.grad[i] = grad[i].multiply(a.value).add(value.multiply(a.grad[i]));
        }
        return result;
    }

It can be a great improvement to also have mathematical methods taking into argument a `RealFieldElement` (i.e. a type T). Here an example for the previous `multiply` method:

    /** '&times;' operator.
     * @param a right hand side parameter of the operator
     * @return this&times;a
     */
    public FieldGradient<T> multiply(final T a) {
        final FieldGradient<T> result = newInstance(value.multiply(a));
        for (int i = 0; i < grad.length; ++i) {
            result.grad[i] = grad[i].multiply(a);
        }
        return result;
    }

I can perform the change with a merge request if you agree with the feature proposal!

Regards,
Bryan

**Comment by maisonobe** [comment]
I agree with this proposal, it seems a good improvement to me.

**Comment by BryanCazabonne** [comment]
Thank you. I will provide a pull request with the implementation this afternoon.

**Comment by BryanCazabonne** [comment]
This issue has been fixed some time ago
